[package]
name = "razor"
version = "0.1.0"
authors = ["Pablo Marques <pablomarques.pessoal@hotmail.com>"]
edition = "2021"

[dependencies]
#Gráficos
ggez = "0.6"

[lib]
name = "core"
path = "src/core/lib.rs"